"""API Schemas package."""

from backend.app.schemas.cpu import (
    AlgorithmType,
    ProcessInput,
    CPUSimulateRequest,
    CPUSimulateResponse,
    GanttSegmentResponse,
    ProcessMetricsResponse,
    AggregateMetricsResponse,
    SimulationEventResponse,
    ProcessSnapshotResponse,
    CPUStateResponse,
    SystemStateResponse,
    PresetItemResponse,
)
from backend.app.schemas.memory import (
    MemoryAlgorithmType,
    MemoryOperationType,
    MemoryOperationInput,
    MemoryBlockResponse,
    MemoryMetricsResponse,
    OperationResultResponse,
    MemoryStateResponse,
    MemoryEventResponse,
    MemorySimulateRequest,
    MemorySimulateResponse,
    MemoryPresetItemResponse,
)

__all__ = [
    "AlgorithmType",
    "ProcessInput",
    "CPUSimulateRequest",
    "CPUSimulateResponse",
    "GanttSegmentResponse",
    "ProcessMetricsResponse",
    "AggregateMetricsResponse",
    "SimulationEventResponse",
    "ProcessSnapshotResponse",
    "CPUStateResponse",
    "SystemStateResponse",
    "PresetItemResponse",
    "MemoryAlgorithmType",
    "MemoryOperationType",
    "MemoryOperationInput",
    "MemoryBlockResponse",
    "MemoryMetricsResponse",
    "OperationResultResponse",
    "MemoryStateResponse",
    "MemoryEventResponse",
    "MemorySimulateRequest",
    "MemorySimulateResponse",
    "MemoryPresetItemResponse",
]
