"""API Schemas package."""

from backend.app.schemas.cpu import (
    AlgorithmType,
    ProcessInput,
    CPUSimulateRequest,
    CPUSimulateResponse,
    GanttSegmentResponse,
    ProcessMetricsResponse,
    AggregateMetricsResponse,
    SimulationEventResponse,
    ProcessSnapshotResponse,
    CPUStateResponse,
    SystemStateResponse,
    PresetItemResponse,
)
from backend.app.schemas.memory import (
    MemoryAlgorithmType,
    MemoryOperationType,
    MemoryOperationInput,
    MemoryBlockResponse,
    MemoryMetricsResponse,
    OperationResultResponse,
    MemoryStateResponse,
    MemoryEventResponse,
    MemorySimulateRequest,
    MemorySimulateResponse,
    MemoryPresetItemResponse,
)

from backend.app.schemas.virtual_memory import (
    VirtualMemoryAlgorithmType,
    VirtualMemorySimulateRequest,
    VirtualMemorySimulateResponse,
    VirtualMemoryPresetItemResponse,
    VirtualMemorySnapshotResponse,
    VirtualMemoryMetricsResponse,
    VirtualMemoryEventResponse,
)

from backend.app.schemas.deadlock import (
    RequestOutcomeEnum,
    GraphNodeResponse,
    GraphEdgeResponse,
    GraphSnapshotResponse,
    SafetyStepResponse,
    DetectionStepResponse,
    RequestEvaluationResponse,
    DeadlockSystemStateResponse,
    DeadlockTimelineSnapshotResponse,
    DeadlockEventResponse,
    DeadlockMetricsResponse,
    DeadlockSafetyRequest,
    DeadlockResourceRequestInput,
    DeadlockDetectRequest,
    DeadlockSimulationResponse,
    DeadlockPresetItemResponse,
)

__all__ = [
    "AlgorithmType",
    "ProcessInput",
    "CPUSimulateRequest",
    "CPUSimulateResponse",
    "GanttSegmentResponse",
    "ProcessMetricsResponse",
    "AggregateMetricsResponse",
    "SimulationEventResponse",
    "ProcessSnapshotResponse",
    "CPUStateResponse",
    "SystemStateResponse",
    "PresetItemResponse",
    "MemoryAlgorithmType",
    "MemoryOperationType",
    "MemoryOperationInput",
    "MemoryBlockResponse",
    "MemoryMetricsResponse",
    "OperationResultResponse",
    "MemoryStateResponse",
    "MemoryEventResponse",
    "MemorySimulateRequest",
    "MemorySimulateResponse",
    "MemoryPresetItemResponse",
    "VirtualMemoryAlgorithmType",
    "VirtualMemorySimulateRequest",
    "VirtualMemorySimulateResponse",
    "VirtualMemoryPresetItemResponse",
    "VirtualMemorySnapshotResponse",
    "VirtualMemoryMetricsResponse",
    "VirtualMemoryEventResponse",
    "RequestOutcomeEnum",
    "GraphNodeResponse",
    "GraphEdgeResponse",
    "GraphSnapshotResponse",
    "SafetyStepResponse",
    "DetectionStepResponse",
    "RequestEvaluationResponse",
    "DeadlockSystemStateResponse",
    "DeadlockTimelineSnapshotResponse",
    "DeadlockEventResponse",
    "DeadlockMetricsResponse",
    "DeadlockSafetyRequest",
    "DeadlockResourceRequestInput",
    "DeadlockDetectRequest",
    "DeadlockSimulationResponse",
    "DeadlockPresetItemResponse",
]

